#!/bin/bash

# Target base folder
BASE_DIR="lib"

echo "📁 Creating base structure in $BASE_DIR ..."

mkdir -p $BASE_DIR/bind
touch $BASE_DIR/bind/home_binding.dart
touch $BASE_DIR/bind/next_binding.dart
touch $BASE_DIR/bind/splash_bindings.dart

mkdir -p $BASE_DIR/core/{api,helpers,languages,themes,utils}

mkdir -p $BASE_DIR/res
touch $BASE_DIR/res/assets.dart

mkdir -p $BASE_DIR/routes
touch $BASE_DIR/routes/pages.dart
touch $BASE_DIR/routes/routes.dart

mkdir -p $BASE_DIR/views/firebase
mkdir -p $BASE_DIR/views/home/{controller,model,screens}
mkdir -p $BASE_DIR/views/splash
touch $BASE_DIR/views/splash/scre.dart

mkdir -p $BASE_DIR/widgets
touch $BASE_DIR/widgets/initial.dart

touch $BASE_DIR/main.dart

echo "✅ Folder and file structure created successfully!"
