#!/bin/bash

for viewName in "$@"; do
  base_dir="lib/views/$viewName"
  echo "📦 Generating view: $viewName"

  mkdir -p "$base_dir/controller"
  mkdir -p "$base_dir/screen"
  mkdir -p "$base_dir/widget"

  # Controller
  cat <<EOF > "$base_dir/controller/${viewName}_controller.dart"
import 'package:get/get.dart';

class ${viewName^}Controller extends GetxController {
  // TODO: Add logic
}
EOF

  # Screen
  cat <<EOF > "$base_dir/screen/${viewName}_mobile_screen.dart"
par of "${viewName}_screen.dart"
class ${viewName^}Screen extends StatelessWidget {
  final controller = Get.put(${viewName^}Controller());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('${viewName^}')),
      body: Center(child: Text('${viewName^} Screen')),
    );
  }
}
EOF




  # Screen 2
  cat <<EOF > "$base_dir/screen/${viewName}_screen.dart"

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../controller/${viewName}_controller.dart';

   part "${viewName}_mobile_screen.dart"

class ${viewName^}Screen extends StatelessWidget {
  final controller = Get.put(${viewName^}Controller());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('${viewName^}')),
      body: Center(child: Text('${viewName^} Screen')),
    );
  }
}
EOF


#!/bin/bash

viewName=$1
shift

widget_dir="lib/views/$viewName/widget"
mkdir -p "$widget_dir"

for widgetName in "$@"; do
  file="$widget_dir/${widgetName}.dart"
  echo "🧱 Generating widget: $widgetName in $widget_dir"

  cat <<EOF > "$file"
import 'package:flutter/material.dart';

class ${widgetName^}Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text('${widgetName^}'),
    );
  }
}
EOF
OKAY----
  echo "✅ View '$viewName' created successfully! "
done
