#!/bin/bash

viewName=$1
shift

widget_dir="lib/views/$viewName/widget"
mkdir -p "$widget_dir"

for widgetName in "$@"; do
  file="$widget_dir/${widgetName}_widget.dart"
  echo "🧱 Generating widget: $widgetName in $widget_dir"

  cat <<EOF > "$file"
import 'package:flutter/material.dart';

class ${widgetName^}Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Text('${widgetName^} Widget'),
    );
  }
}
EOF
done

echo "✅ All widgets created inside $widget_dir"
